-- ============================================================
-- FIX: "permission denied for table vendedor_reportes/preguntas"
-- Correr en Supabase → SQL Editor → New query → Run
-- Es idempotente: se puede correr varias veces sin problema.
-- ============================================================

-- 1) Asegurar que las tablas existan (si ya existen, no las toca)
create table if not exists public.vendedor_reportes (
  id             bigint generated by default as identity primary key,
  telefono       text        not null,
  nombre         text,
  fecha          date        not null,
  ventas         integer     not null default 0,
  actualizado_at timestamptz not null default now()
);

create table if not exists public.vendedor_preguntas (
  id            bigint generated by default as identity primary key,
  telefono      text        not null,
  tipo          text        not null default 'hoy',   -- 'hoy' | 'ayer'
  enviado_at    timestamptz not null default now(),
  respondido_at timestamptz,
  respuesta_seg integer
);

-- Índices útiles para las consultas del panel
create index if not exists idx_vr_fecha  on public.vendedor_reportes (fecha);
create index if not exists idx_vr_tel     on public.vendedor_reportes (telefono);
create index if not exists idx_vp_tel_env on public.vendedor_preguntas (telefono, enviado_at);

-- 2) LA CAUSA DEL 0/13: dar permisos al rol que usa el backend (service_role)
--    y a los roles estándar de Supabase.
grant all on table public.vendedor_reportes  to service_role, anon, authenticated;
grant all on table public.vendedor_preguntas to service_role, anon, authenticated;

-- Permisos sobre las secuencias (identity) para poder insertar
grant usage, select on all sequences in schema public to service_role, anon, authenticated;

-- 3) El backend entra con service_role (salta RLS). Dejamos RLS desactivado
--    porque es una herramienta interna sin usuarios finales.
alter table public.vendedor_reportes  disable row level security;
alter table public.vendedor_preguntas disable row level security;

-- 4) Verificación rápida (debería devolver 0 filas hoy, sin error)
select count(*) as reportes_hoy
from public.vendedor_reportes
where fecha = (now() at time zone 'America/Bogota')::date;
