-- ============================================================
-- Análisis de chats perdidos: guarda por qué NO compraron.
-- Correr en Supabase -> SQL Editor -> Run (idempotente).
-- ============================================================

create table if not exists public.objeciones_analisis (
  id              bigint generated by default as identity primary key,
  fecha           date        not null,
  conversation_id text        not null,
  categoria       text        not null,   -- Precio | Desconfianza | Talla | Envío | Indecisión | Producto | Sin respuesta | Otro
  detalle         text,                    -- resumen corto de por qué no compró
  cita            text,                    -- frase textual del chat que lo respalda
  created_at      timestamptz not null default now()
);

create index if not exists idx_obj_fecha on public.objeciones_analisis (fecha);
create index if not exists idx_obj_cat   on public.objeciones_analisis (categoria);
create index if not exists idx_obj_conv  on public.objeciones_analisis (conversation_id, fecha);

-- Permisos (el backend entra con service_role)
grant all on table public.objeciones_analisis to service_role, anon, authenticated;
grant usage, select on all sequences in schema public to service_role, anon, authenticated;
alter table public.objeciones_analisis disable row level security;
